# Generated by Django 3.2.5 on 2021-08-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textutils', '0002_alter_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactmodal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namemodal', models.CharField(max_length=30)),
                ('emailmodal', models.EmailField(max_length=254)),
                ('textmodal', models.TextField(max_length=600)),
            ],
        ),
    ]
