# Generated by Django 3.2.5 on 2021-08-01 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textutils', '0003_contactmodal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmodal',
            old_name='emailmodal',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contactmodal',
            old_name='namemodal',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contactmodal',
            old_name='textmodal',
            new_name='text',
        ),
    ]
