# Generated by Django 3.2.5 on 2021-08-01 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textutils', '0004_auto_20210801_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmodal',
            old_name='email',
            new_name='emailmodal',
        ),
        migrations.RenameField(
            model_name='contactmodal',
            old_name='name',
            new_name='namemodal',
        ),
        migrations.RenameField(
            model_name='contactmodal',
            old_name='text',
            new_name='textmodal',
        ),
    ]
